Capstone.Web/Controllers/PlannerController.cs
using Microsoft.AspNetCore.Mvc;
using Capstone.Data;
using Microsoft.EntityFrameworkCore;

namespace Capstone.Controllers
{
    public class PlannerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PlannerController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.ToDoLists.Include(t => t.Items).ToListAsync());
        }
        public async Task<IActionResult> Today()
        {
            var todayItems = await _context.ToDoLists
                                           .Include(t => t.Items)
                                           .Where(t => t.Items.Any(i => i.DueDate.Date == DateTime.Now.Date))
                                           .ToListAsync();
            return View(todayItems);
        }

        public async Task<IActionResult> Planned()
        {
            var startDate = DateTime.Now.Date;
            var endDate = startDate.AddDays(7);

            var plannedItems = await _context.ToDoLists
                                             .Include(t => t.Items)
                                             .Where(t => t.Items.Any(i => i.DueDate.Date >= startDate && i.DueDate.Date <= endDate))
                                             .ToListAsync();
            return View(plannedItems);
        }

    }
}

Capstone.Web/Views/Planner/Index.cshtml
@model IEnumerable<Capstone.Data.Models.ToDoList>

<h3 class="mb-4">Planner</h3>

<a href="@Url.Action("Today", "Planner")">
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">Today</h5>
            <p class="card-text">@Model.SelectMany(x => x.Items).Where(x => x.DueDate.Date == DateTime.Now.Date).Count()</p>
        </div>
    </div>
</a>

<a href="@Url.Action("Planned", "Planner")">
    <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">Planned</h5>
            <p class="card-text">@Model.SelectMany(x => x.Items).Where(x => x.DueDate.Date >= DateTime.Now.Date && x.DueDate.Date <= DateTime.Now.Date.AddDays(7)).Count()</p>
        </div>
    </div>
</a>

Capstone.Web/Views/Planner/Planned.cshtml
@model IEnumerable<Capstone.Data.Models.ToDoList>

<h3 class="mb-4">Planned Tasks for the Next 7 Days</h3>

@if (!Model.Any())
{
    <p>No planned tasks for the next 7 days.</p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Due Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var toDoList in Model)
            {
                foreach (var item in toDoList.Items)
                {
                    if (item.DueDate.Date >= DateTime.Now.Date && item.DueDate.Date <= DateTime.Now.Date.AddDays(7))
                    {
                        <tr>
                            <td>@item.Title</td>
                            <td>@item.Description</td>
                            <td>@item.DueDate.ToShortDateString()</td>
                        </tr>
                    }
                }
            }
        </tbody>
    </table>
}

Capstone.Web/Views/Planner/Today.cshtml
@model IEnumerable<Capstone.Data.Models.ToDoList>

<h3 class="mb-4">Tasks for Today</h3>

@if (!Model.Any())
{
    <p>No tasks for today.</p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Due Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var toDoList in Model)
            {
                foreach (var item in toDoList.Items)
                {
                    if (item.DueDate.Date == DateTime.Now.Date)
                    {
                        <tr>
                            <td>@item.Title</td>
                            <td>@item.Description</td>
                            <td>@item.DueDate.ToShortDateString()</td>
                        </tr>
                    }
                }
            }
        </tbody>
    </table>
}