Capstone.Web/Controllers/ToDoController.cs
using Microsoft.AspNetCore.Mvc;
using Capstone.Data;
using Capstone.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Capstone.Data.Enums;


namespace Capstone.Controllers
{
    public class ToDoController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<ToDoController> _logger;


        public ToDoController(ApplicationDbContext context, ILogger<ToDoController> logger)
        {
            _context = context;
            _logger = logger;
        }


        public async Task<IActionResult> Index()
        {
            var uncompletedTasksCount = _context.ToDoItems.Count();

            return View(await _context.ToDoLists.Include(t => t.Items).ToListAsync());
        }

        public async Task<IActionResult> Planner()
        {
            return View(await _context.ToDoLists.Include(t => t.Items).ToListAsync());
        }

        public IActionResult View(int id)
        {
            var toDoList = _context.ToDoLists
                                   .Include(t => t.Items)
                                   .SingleOrDefault(t => t.Id == id);
            if (toDoList == null)
            {
                return NotFound();
            }

            return View(toDoList);
        }

        // GET: ToDo/CreateList
        public IActionResult Create()
        {
            return View();
        }

        // POST: ToDo/CreateList
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name")] ToDoList toDoList)
        {
            if (ModelState.IsValid)
            {
                _context.Add(toDoList);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(toDoList);
        }

        // GET: ToDo/EditList/5
        public async Task<IActionResult> EditList(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toDoList = await _context.ToDoLists.FindAsync(id);
            if (toDoList == null)
            {
                return NotFound();
            }
            return View("Edit", toDoList);
        }

        // POST: ToDo/EditList/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditList(int id, [Bind("Id,Name")] ToDoList toDoList)
        {
            if (id != toDoList.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(toDoList);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ToDoListExists(toDoList.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(toDoList);
        }

        // GET: ToDo/DeleteList/5
        public async Task<IActionResult> DeleteList(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toDoList = await _context.ToDoLists
                .Include(t => t.Items)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (toDoList == null)
            {
                return NotFound();
            }

            return View(toDoList);
        }

        // POST: ToDo/DeleteList/5
        [HttpPost, ActionName("DeleteList")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteListConfirmed(int id)
        {
            var toDoList = await _context.ToDoLists.FindAsync(id);
            _context.ToDoLists.Remove(toDoList);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ToDoListExists(int id)
        {
            return _context.ToDoLists.Any(e => e.Id == id);
        }

        // GET: ToDo/CreateItem
        public IActionResult CreateItem(string currentListId)
        {
            ViewBag.CurrentListId = currentListId;
            ViewBag.ToDoListId = new SelectList(_context.ToDoLists, "Id", "Name");
            return View();
        }

        // POST: ToDo/CreateItem
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateItem([Bind("Title,Description,DueDate,CreationDate,Status,ToDoListId")] ToDoItem toDoItem)
        {            
            if (ModelState.IsValid)
            {
                _context.Add(toDoItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewBag.ToDoListId = new SelectList(_context.ToDoLists, "Id", "Name", toDoItem.ToDoListId);
            return View(toDoItem);
        }

        // GET: ToDo/EditItem/5
        public async Task<IActionResult> EditItem(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toDoItem = await _context.ToDoItems.FindAsync(id);
            if (toDoItem == null)
            {
                return NotFound();
            }
            ViewBag.ToDoListId = new SelectList(_context.ToDoLists, "Id", "Name", toDoItem.ToDoListId);
            return View(toDoItem);
        }

        // POST: ToDo/EditItem/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditItem(int id, [Bind("Id,Title,Description,DueDate,CreationDate,Status,ToDoListId")] ToDoItem toDoItem)
        {
            if (id != toDoItem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(toDoItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ToDoItemExists(toDoItem.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("View", new { id = toDoItem.ToDoListId });
            }
            ViewBag.ToDoListId = new SelectList(_context.ToDoLists, "Id", "Name", toDoItem.ToDoListId);
            return View(toDoItem);
        }

        // GET: ToDo/DeleteItem/5
        public async Task<IActionResult> DeleteItem(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toDoItem = await _context.ToDoItems
                .Include(t => t.ToDoList)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (toDoItem == null)
            {
                return NotFound();
            }

            return View(toDoItem);
        }

        // POST: ToDo/DeleteItem/5
        [HttpPost, ActionName("DeleteItem")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteItemConfirmed(int id)
        {
            var toDoItem = await _context.ToDoItems.FindAsync(id);
            _context.ToDoItems.Remove(toDoItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> CompleteItem(int id)
        {
            var task = await _context.ToDoItems.FindAsync(id);
            if (task == null)
            {
                return NotFound();
            }

            task.Status = Status.Completed;
            _context.Update(task);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(View), new { id = task.ToDoListId });
        }

        [HttpPost]
        public async Task<IActionResult> DuplicateList(int id)
        {
            var originalList = await _context.ToDoLists
                                             .Include(t => t.Items)
                                             .SingleOrDefaultAsync(t => t.Id == id);

            if (originalList == null)
            {
                return NotFound();
            }

            // Create a new list based on the original
            var newList = new ToDoList
            {
                Name = originalList.Name + " (Copy)"  // You can modify this naming pattern as per your needs
            };

            _context.ToDoLists.Add(newList);
            await _context.SaveChangesAsync();  // Save the new list to get its Id

            // Copy items from the original list to the new list
            foreach (var item in originalList.Items)
            {
                var newItem = new ToDoItem
                {
                    Title = item.Title,
                    Description = item.Description,
                    DueDate = item.DueDate,
                    CreationDate = DateTime.Now,  // Set current date as creation date for the copied item
                    Status = item.Status,
                    ToDoListId = newList.Id
                };

                _context.ToDoItems.Add(newItem);
            }

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(View), new { id = newList.Id });
        }

        public IActionResult PrivacyPolicy()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddComment(int toDoItemId, string commentText)
        {
            var toDoItem = await _context.ToDoItems.FindAsync(toDoItemId);
            if (toDoItem == null)
            {

Capstone.Web/Views/ToDo/Comments.cshtml
@model Capstone.Data.Models.ToDoItem

@{
    ViewData["Title"] = "Comments";
}

<div class="container mt-5">
    <h3 class="mb-4">@Model.Title</h3>

    <label class="d-block">Description:</label>
    <p style="background-color: #f5f5f5; padding: 10px; color: #333;">@Model.Description</p>

    <label class="d-block">Due Date:</label>
    <p style="background-color: #f5f5f5; padding: 10px; color: #333;">@Model.DueDate.ToShortDateString()</p>

    <h4 class="mb-3">Comments</h4>

    @foreach (var comment in Model.Comments)
    {
        <div class="card mb-3 clickable">
            <div class="card-body">
                <p>@comment.Text</p>
                <small>@comment.CreationDate.ToShortDateString()</small>
                <form asp-action="DeleteComment" method="post" class="d-inline-block ml-3">
                    <input type="hidden" name="commentId" value="@comment.Id" />
                    <button type="submit" class="btn btn-link p-0 add-icon" title="Delete">
                        <i class="fas fa-trash-alt"></i>
                    </button>
                </form>
            </div>
        </div>
    }

    <h5 class="mb-3">Add Comment</h5>
    <form asp-action="AddComment" asp-controller="ToDo" method="post">
        <input type="hidden" name="toDoItemId" value="@Model.Id" />
        <div class="form-group">
            <textarea name="commentText" required class="form-control"></textarea>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Add Comment</button>
    </form>

    <div class="mt-4">
        <a asp-action="View" asp-route-id="@Model.ToDoListId" class="back-icon add-icon">
            <i class="fas fa-arrow-left"></i>&nbsp;Back
        </a>
    </div>
</div>

Capstone.Web/Views/ToDo/Create.cshtml
@model Capstone.Data.Models.ToDoList
@{
    ViewData["Title"] = "Create New To-Do List";
}

<h3 class="mb-4">@ViewData["Title"]</h3>

<form asp-action="Create">
    <div class="form-group">
        <label asp-for="Name">List Name</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="mt-4">
        <button type="submit" class="btn-icon mr-3" title="Save">
            <i class="fas fa-save"></i>
            Create New To-Do List
        </button>
    </div>
</form>

<a href="@Url.Action("Index", "ToDo")" class="back-icon add-icon" title="Back to Lists">
    <i class="fas fa-arrow-left"></i>
    Back
</a>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Capstone.Web/Views/ToDo/CreateItem.cshtml
@model Capstone.Data.Models.ToDoItem
@{
    ViewData["Title"] = "Create To-Do Item";
}

<div class="container mt-5">
    <h3 class="mb-4">@ViewData["Title"]</h3>

    <form asp-action="CreateItem">
        <div class="form-group">
            <label asp-for="Title">Title</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description">Description</label>
            <textarea asp-for="Description" class="form-control"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="DueDate">Due Date</label>
            <input asp-for="DueDate" type="date" class="form-control" />
            <span asp-validation-for="DueDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ToDoListId">To-Do List</label>
            <select asp-for="ToDoListId" class="form-control" asp-items="ViewBag.ToDoListId"></select>
            <span asp-validation-for="ToDoListId" class="text-danger"></span>
        </div>
        <div class="mt-4">
            <button type="submit" class="btn-icon mr-3" title="Save">
                <i class="fas fa-save"></i>
                Create To-Do Item
            </button>
            <a href="@Url.Action("View", "ToDo", new { id = ViewBag.CurrentListId })" class="back-icon add-icon" title="Back without saving">
                <i class="fas fa-arrow-left"></i>
                Back
            </a>
        </div>
    </form>

</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Capstone.Web/Views/ToDo/DeleteItem.cshtml
@model Capstone.Data.Models.ToDoItem
@{
    ViewData["Title"] = "Delete To-Do Item";
}

<h3 class="mb-4">@ViewData["Title"]</h3>

<p>Are you sure you want to delete this item?</p>
<h4>@Model.Title</h4>

<form asp-action="DeleteItem">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-danger">Delete</button>
    <a asp-action="View" asp-route-id="@Model.ToDoListId" class="btn btn-secondary">Cancel</a>
</form>

Capstone.Web/Views/ToDo/DeleteList.cshtml
@model Capstone.Data.Models.ToDoList
@{
    ViewData["Title"] = "Delete To-Do List";
}

<h3 class="mb-4">@ViewData["Title"]</h3>

<p>Are you sure you want to delete the list "@Model.Name" and all its items?</p>

<form asp-action="DeleteList">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-danger">Delete</button>
    <a asp-action="View" asp-route-id="@Model.Id" class="btn btn-secondary">Cancel</a>
</form>

Capstone.Web/Views/ToDo/Edit.cshtml
@model Capstone.Data.Models.ToDoList
@{
    ViewData["Title"] = "Edit To-Do List";
}

<h3 class="mb-4">@ViewData["Title"]</h3>

<form asp-action="EditList">
    <input type="hidden" asp-for="Id" /> <!-- To keep track of which list we're editing -->

    <div class="form-group">
        <label asp-for="Name">List Name</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="mt-4">
        <button type="submit" class="btn-icon mr-3" title="Save Changes">
            <i class="fas fa-save fa-2x"></i>
        </button>
        <a href="@Url.Action("View", "ToDo", new { id = Model.Id })" class="back-icon add-icon" title="Back without saving">
            <i class="fas fa-arrow-left fa-2x"></i>
        </a>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Capstone.Web/Views/ToDo/EditItem.cshtml
@model Capstone.Data.Models.ToDoItem

<h3 class="mb-4">Edit ToDo Item</h3>


<form asp-action="EditItem" method="post">
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
    </div>

    <div class="form-group">
        <label asp-for="DueDate"></label>
        <input asp-for="DueDate" class="form-control" type="date" />
    </div>

    <div class="form-group">
        <label asp-for="CreationDate"></label>
        <input asp-for="CreationDate" class="form-control" type="date" />
    </div>

    <div class="form-group">
        <label asp-for="Status"></label>
        <select asp-for="Status" class="form-control">
            @foreach (Status status in Enum.GetValues(typeof(Status)))
            {
                <option value="@status">@Extensions.GetDisplayName(status)</option>
            }
        </select>
    </div>

    <div class="form-group">
        <label asp-for="ToDoListId">ToDo List</label>
        <select asp-for="ToDoListId" asp-items="ViewBag.ToDoListId" class="form-control"></select>
    </div>

    <br />

    <button type="submit" class="btn btn-secondary">Save</button>

    <div class="mt-4">
        <a href="@Url.Action("Index", "ToDo")" class="back-icon add-icon" title="Back to Lists">
            <i class="fas fa-arrow-left"></i>&nbsp;Back
        </a>
    </div>

</form>

Capstone.Web/Views/ToDo/Index.cshtml
@model IEnumerable<Capstone.Data.Models.ToDoList>

@{
    ViewData["Title"] = "ToDo Lists";
}

<h3 class="mb-4">@ViewData["Title"]</h3>

<div class="container mt-5">
    <p>
        <a href="@Url.Action("Create", "ToDo")" class="add-icon mr-3" title="Create New List">
            <i class="fas fa-plus-circle"></i>
            Create New List
        </a>        
    </p>    

    @foreach (var toDoList in Model)
    {
        <a href="@Url.Action("View", "ToDo", new { id = toDoList.Id })" class="text-decoration-none">
            <div class="card mb-3 clickable">
                <div class="card-body">
                    <h5 class="card-title">
                        <i class="fas fa-list-ul"></i> @toDoList.Name
                    </h5>
                    <p class="card-text">@toDoList.Items.Count() tasks</p>
                </div>
            </div>
        </a>
    }

</div>

Capstone.Web/Views/ToDo/PrivacyPolicy.cshtml
<div id="privacy-policy-page">
<h1>Privacy Policy for ToDo app</h1>
<h2>Introduction</h2>
<p>Thank you for choosing to be part of our community at Darya Trafimenka (“Company”, “we”, “us”, “our”). We are committed to protecting your personal information and your right to privacy. If you have any questions or concerns about this privacy notice or our practices regarding your personal information, please contact us at makynja1991@gmail.com.</p>

<p>This privacy notice describes how we might use your information if you:</p>
<ul>
    <li>Visit our website</li>
    <li>Use our mobile application</li>
    <li>Engage with us in other related ways, including any sales or marketing activities</li>
</ul>

<h2>Information We Collect</h2>
<p>The personal information you provide can give away a lot of information about you. The public availability of your information is your choice. The information you provide us during account creation and setup is secured and is not used by us or sold to any third parties. We collect information solely for the purpose of the app's functionality and improvement.</p>

<h2>How We Use Your Information</h2>
<p>We use the information we collect or receive:</p>
<ul>
    <li>To send you marketing and promotional communications.</li>
    <li>To deliver targeted advertising to you.</li>
    <li>To request feedback and contact you about your use of our app.</li>
</ul>

<h2>How We Keep Your Information Safe</h2>
<p>We aim to protect your personal information through a system of organizational and technical security measures.</p>

<h2>Links to Other Websites</h2>
<p>Our app may contain links to other websites that are not operated by us. This Privacy Policy does not apply to third-party websites/services.</p>

<h2>Updates to This Privacy Policy</h2>
<p>We may update this privacy policy from time to time. The updated version will be indicated by an updated "Last updated" date.</p>

<h2>Contact Us</h2>
<p>If you have questions or comments about this policy, you may contact us at makynja1991@gmail.com.</p>
</div>

Capstone.Web/Views/ToDo/View.cshtml
@model Capstone.Data.Models.ToDoList

@{
    ViewData["Title"] = Model.Name;
}

<div class="container mt-5">
    <h3 class="mb-4">@ViewData["Title"]</h3>

    <!-- Action Links below the title -->
    <div class="d-flex justify-content-between align-items-center mb-3">
        <a href="@Url.Action("CreateItem", "ToDo", new { currentListId = Model.Id })" class="mr-3 add-icon" title="Add Item">
            <i class="fas fa-plus-circle"></i> Add Item
        </a>
        <a href="@Url.Action("EditList", "ToDo", new { id = Model.Id })" class="add-icon" title="Edit">
            <i class="fas fa-edit"></i> Edit
        </a>
        <form asp-action="DuplicateList" asp-route-id="@Model.Id" method="post" class="d-inline-block">
            <button type="submit" class="btn btn-link p-0 ml-2 add-icon" title="Duplicate">
                <i class="fas fa-copy"></i> Duplicate
            </button>
        </form>
        <a href="@Url.Action("DeleteList", "ToDo", new { id = Model.Id })" class="add-icon" title="Delete">
            <i class="fas fa-trash-alt"></i> Delete
        </a>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Status</th>
                <th>Title</th>                
                <th>Due Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var task in Model.Items)
            {
                <tr>
                    <td><i class="@task.Status.GetFontAwesomeIcon()"></i></td>
                    <td><a href="@Url.Action("Comments", "ToDo", new { id = task.Id })">@task.Title</a></td> <!--new code @* <td>@task.Title</td> *@-->
                    <td>@task.DueDate.ToShortDateString()</td>
                    <td>
                        <a asp-action="EditItem" asp-route-id="@task.Id" title="Edit">
                            <button title="Edit">
                                <i class="fas fa-edit"></i>
                            </button>
                        </a>
                        <a asp-action="DeleteItem" asp-route-id="@task.Id" title="Delete">
                            <button title="Delete">
                                <i class="fas fa-trash-alt"></i>
                            </button>                     
                        </a>
                        &nbsp;
                        <form asp-action="CompleteItem" asp-route-id="@task.Id" method="post" class="d-inline-block">
                            @if (task.Status != Capstone.Data.Enums.Status.Completed)
                            {
                                <button type="submit" title="Complete">
                                    <i class="fas fa-check"></i>
                                </button>
                            }
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div class="mt-4">
        <a href="@Url.Action("Index", "ToDo")" class="back-icon add-icon" title="Back to Lists">
            <i class="fas fa-arrow-left"></i>&nbsp;Back
        </a>
    </div>
</div>